Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-13"

  config.vm.hostname = "lamp-server"

  # 3) Port forwarding : hôte 7676 -> VM 80
  config.vm.network "forwarded_port", guest: 80, host: 7676

  # 4) Dossier partagé : ./shared -> /var/www/html
  config.vm.synced_folder "./shared", "/var/www/html",
    owner: "www-data",
    group: "www-data",
    mount_options: ["dmode=755", "fmode=644"]

  # 5) Ressources VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "lamp-server"
    vb.memory = 1024
    vb.cpus   = 1
  end

  # 6) Provisionnement via script shell externe
  config.vm.provision "shell", path: "provision.sh"
end
